"""inicial

Revision ID: 0d6738a254ce
Revises: 
Create Date: 2026-07-20 22:15:06.853974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d6738a254ce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dev_incremento_percentual', sa.Float(), nullable=True),
    sa.Column('dev_tempo_base_horas', sa.Float(), nullable=True),
    sa.Column('dev_tempo_fator_horas', sa.Float(), nullable=True),
    sa.Column('dev_custo_base', sa.Float(), nullable=True),
    sa.Column('dev_custo_fator', sa.Float(), nullable=True),
    sa.Column('treino_incremento_percentual', sa.Float(), nullable=True),
    sa.Column('treino_tempo_base_horas', sa.Float(), nullable=True),
    sa.Column('treino_tempo_fator_horas', sa.Float(), nullable=True),
    sa.Column('treino_custo_base', sa.Float(), nullable=True),
    sa.Column('treino_custo_fator', sa.Float(), nullable=True),
    sa.Column('pit_tempo_sem_treino', sa.Float(), nullable=True),
    sa.Column('pit_tempo_treino_completo', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fornecedores_cambio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('custo_temporada', sa.Float(), nullable=True),
    sa.Column('custo_montagem', sa.Float(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('performance', sa.Float(), nullable=True),
    sa.Column('categoria_pista', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fornecedores_chassi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('custo_temporada', sa.Float(), nullable=True),
    sa.Column('custo_montagem', sa.Float(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('performance', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fornecedores_combustivel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('custo_temporada', sa.Float(), nullable=True),
    sa.Column('custo_montagem', sa.Float(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('eficiencia', sa.Float(), nullable=True),
    sa.Column('aumento_potencia_motor', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fornecedores_engenheiro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('custo_temporada', sa.Float(), nullable=True),
    sa.Column('custo_montagem', sa.Float(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('nivel', sa.Integer(), nullable=True),
    sa.Column('eficiencia_exata', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fornecedores_motor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('custo_temporada', sa.Float(), nullable=True),
    sa.Column('custo_montagem', sa.Float(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('potencia', sa.Float(), nullable=True),
    sa.Column('eficiencia_combustivel', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fornecedores_pneu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('custo_temporada', sa.Float(), nullable=True),
    sa.Column('custo_montagem', sa.Float(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('performance', sa.Float(), nullable=True),
    sa.Column('desgaste', sa.Float(), nullable=True),
    sa.Column('categoria_chuva', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fornecedores_suspensao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('custo_temporada', sa.Float(), nullable=True),
    sa.Column('custo_montagem', sa.Float(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('performance', sa.Float(), nullable=True),
    sa.Column('categoria_pista', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('temporadas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=True),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('eh_admin', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('grupo', sa.String(length=50), nullable=True),
    sa.Column('classe', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('google_id')
    )
    op.create_table('carros_jogadores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('orcamento', sa.Float(), nullable=True),
    sa.Column('motor_fornecedor_id', sa.Integer(), nullable=False),
    sa.Column('combustivel_fornecedor_id', sa.Integer(), nullable=False),
    sa.Column('pneu_fornecedor_id', sa.Integer(), nullable=False),
    sa.Column('chassi_fornecedor_id', sa.Integer(), nullable=False),
    sa.Column('cambio_fornecedor_id', sa.Integer(), nullable=False),
    sa.Column('suspensao_fornecedor_id', sa.Integer(), nullable=False),
    sa.Column('engenheiro_fornecedor_id', sa.Integer(), nullable=True),
    sa.Column('combustivel_carregado', sa.Float(), nullable=True),
    sa.Column('cor_primaria', sa.String(length=7), nullable=True),
    sa.Column('cor_secundaria', sa.String(length=7), nullable=True),
    sa.ForeignKeyConstraint(['cambio_fornecedor_id'], ['fornecedores_cambio.id'], ),
    sa.ForeignKeyConstraint(['chassi_fornecedor_id'], ['fornecedores_chassi.id'], ),
    sa.ForeignKeyConstraint(['combustivel_fornecedor_id'], ['fornecedores_combustivel.id'], ),
    sa.ForeignKeyConstraint(['engenheiro_fornecedor_id'], ['fornecedores_engenheiro.id'], ),
    sa.ForeignKeyConstraint(['motor_fornecedor_id'], ['fornecedores_motor.id'], ),
    sa.ForeignKeyConstraint(['pneu_fornecedor_id'], ['fornecedores_pneu.id'], ),
    sa.ForeignKeyConstraint(['suspensao_fornecedor_id'], ['fornecedores_suspensao.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_table('corridas_agendadas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('temporada_id', sa.Integer(), nullable=False),
    sa.Column('pista_real_id', sa.Integer(), nullable=False),
    sa.Column('pista_nome', sa.String(length=120), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('executada', sa.Boolean(), nullable=False),
    sa.Column('data_execucao', sa.DateTime(), nullable=True),
    sa.Column('resultado_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['temporada_id'], ['temporadas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('desenvolvimentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipe_id', sa.Integer(), nullable=False),
    sa.Column('percentual', sa.Float(), nullable=True),
    sa.Column('em_progresso', sa.Boolean(), nullable=True),
    sa.Column('inicio_em', sa.DateTime(), nullable=True),
    sa.Column('horario_conclusao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['equipe_id'], ['carros_jogadores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('equipe_id')
    )
    op.create_table('resultados_classificacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipe_id', sa.Integer(), nullable=False),
    sa.Column('tempo_classificacao', sa.Float(), nullable=True),
    sa.Column('posicao_grid', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['equipe_id'], ['carros_jogadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resultados_corrida',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipe_id', sa.Integer(), nullable=False),
    sa.Column('tempo_total_segundos', sa.Float(), nullable=True),
    sa.Column('pit_stops', sa.Integer(), nullable=True),
    sa.Column('posicao_final', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['equipe_id'], ['carros_jogadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('treinamentos_box',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipe_id', sa.Integer(), nullable=False),
    sa.Column('percentual', sa.Float(), nullable=True),
    sa.Column('em_progresso', sa.Boolean(), nullable=True),
    sa.Column('inicio_em', sa.DateTime(), nullable=True),
    sa.Column('horario_conclusao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['equipe_id'], ['carros_jogadores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('equipe_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('treinamentos_box')
    op.drop_table('resultados_corrida')
    op.drop_table('resultados_classificacao')
    op.drop_table('desenvolvimentos')
    op.drop_table('corridas_agendadas')
    op.drop_table('carros_jogadores')
    op.drop_table('usuarios')
    op.drop_table('temporadas')
    op.drop_table('fornecedores_suspensao')
    op.drop_table('fornecedores_pneu')
    op.drop_table('fornecedores_motor')
    op.drop_table('fornecedores_engenheiro')
    op.drop_table('fornecedores_combustivel')
    op.drop_table('fornecedores_chassi')
    op.drop_table('fornecedores_cambio')
    op.drop_table('configuracao')
    # ### end Alembic commands ###
