"""orcamento_inicial

Revision ID: bb78bfb040a1
Revises: 0d6738a254ce
Create Date: 2026-07-20 23:10:57.587125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb78bfb040a1'
down_revision = '0d6738a254ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuracao', schema=None) as batch_op:
        batch_op.alter_column('orcamento_inicial',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(55000.0)'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuracao', schema=None) as batch_op:
        batch_op.alter_column('orcamento_inicial',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(55000.0)'))

    # ### end Alembic commands ###
